### PR TITLE
Add gpu support for evaluate to enhance module

### PR DESCRIPTION
**Pull request by alxmamaev**
I'm using this tool to preprocess noisy audios for training TTS models. And I need a use case where I can process gigabytes of audios. On CPU it takes so much time. I'm added GPU support to enhance the inference module. That's boosted my code 26 times.

### CODE REVIEW

**Comment by alxmamaev** [comment]
I've signed the license, how to restart the check?

**Comment by adefossez** [comment]
Hey @alxmamaev , thanks for your interest in this project. There is already an option on the command line (`--device cuda`) to use CUDA for prediction, is it not working for you?

**Comment by alxmamaev** [comment]
I'm sorry, my mistake. I just missed this argument, when checked the code.

**Comment by adefossez** [comment]
No worries, I'll close this pool request then :)

**Pull request closed without merging**
